
# Chinese menus

[[docs]]
  name = "关于流影"
  weight = 1
  identifier = "about"
  url = "/about/"

[[docs]]
  name = "快速开始"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started/"

[[docs]]
  name = "编译安装"
  weight = 15
  identifier = "installation"
  url = "/installation/"

# Core languages.zh.menus

[[docs]]
  name = "用户手册"
  weight = 20
  identifier = "user-manual"
  post = "expanded"
  url = "/user-manual/"

[[docs]]
  name = "演示Demo"
  weight = 90
  identifier = "demo"
  url = "/demo/"


# LOW LEVEL ITEMS
#[[docs]]
#  name = "故障排除"
#  weight = 60
#  identifier = "troubleshooting"
#  url = "/zh/troubleshooting/"
#
#[[docs]]
#  name = "工具"
#  weight = 70
#  identifier = "tools"
#  url = "/zh/tools/"
#
#[[docs]]
#  name = "托管与部署"
#  weight = 80
#  identifier = "hosting-and-deployment"
#  url = "/zh/hosting-and-deployment/"
#
[[docs]]
  name = "欢迎贡献"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/contribute/"


[[global]]
  name = "新闻&博客"
  weight = 1
  identifier = "news"
  url = "/news/"

[[global]]
  name = "文档"
  weight = 5
  identifier = "docs"
  url = "/documentation/"


[[global]]
  name = "Demo体验"
  weight = 20
  identifier = "demo"
  url = "/demo/"

# Anything with a weight > 100 gets an external icon
[[global]]
  name = "Gitee"
  weight = 150
  icon = true
  identifier = "gitee"
  post = "external"
  url = "https://gitee.com/organizations/abyssalfish-os/projects"

[[global]]
  name = "GitHub"
  weight = 200
  identifier = "github"
  post = "external"
  url = "https://github.com/orgs/Abyssal-Fish-Technology/repositories"

[[global]]
  name = "讨论区"
  weight = 250
  identifier = "gitter"
  post = "external"
  url = "https://gitter.im/abyssalfish-os/community"
